version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot-keu
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
